### ISSUE TITLE
http://wry.me/bytebeat/ is offline

### ISSUE THREAD

**Issue by homecoded** [darius/bytebeat#2]
Hey Darius,

seems like your website is down. 

http://wry.me/bytebeat/

**Comment by darius** [comment]
You're right -- sorry! It might take me a few weeks to get to it.

**Comment by homecoded** [comment]
No problem. Just thought I let you know. Sometimes my stuff breaks and I don't find out until someone points me at it. By the way, I mentioned your bytebeat-toy in an article for the SCREENGUIDE magazine that I wrote a while back (about bytebeat). When I went over the article again I found that one link not working anymore. 

I like your work! Keep it up :)
