### ISSUE TITLE
Adding the exemple library to scores user-library

### ISSUE THREAD

**Issue by thibaudk** [darius/bytebeat#4]
Hi,

As the opensource "meta sequencer" [score](https://github.com/ossia/score) now supports just in time byte Beat compilation,
we would love to include your extensive list of [examples](http://wry.me/bytebeat/examples.html) to the [score user library](https://github.com/ossia/score-user-library), as we have done with [Faust](https://github.com/ossia/score-user-library/tree/master/Presets/Faust) and [VIDVOX's GLSL shaders library](https://github.com/ossia/score-user-library/tree/master/Presets/GLSL_shaders).

We will of course make sure that the pieces and their creators are properly credited. 

Cheers !
The OSSIA team

**Comment by darius** [comment]
Sorry I'm late to answer, and that I forgot to include a license in this repo.

As noted on my examples page, the examples were all from viznut's collection; I only converted the format. If remember right, viznut collected them from a pouet forum thread having many different posters. If any permission is needed, it'd be from viznut.

**Comment by thibaudk** [comment]
Ok, thank you for your answer, I will contact viznut.
Well done on this repo by the way, it's such a fun way to experiment !
We hope to make score just as immediate.

Best,
Thibaud
